// prettier-ignore
export const tagTypes: string[] = [
  'Select Tag...',
  'Acai Bowls',
  'Afghan',
  'African',
  'Alentejo',
  'Algarve',
  'Alsatian',
  'Altoatesine',
  'American',
  'American',
  'Andalusian',
  'Apulian',
  'Arab Pizza',
  'Arabian',
  'Argentine',
  'Armenian',
  'Arroceria / Paella',
  'Asian Fusion',
  'Asturian',
  'Australian',
  'Austrian',
  'Auvergnat',
  'Azores',
  'Backshop',
  'Baden',
  'Bagels',
  'Baguettes',
  'Bakeries',
  'Bangladeshi',
  'Barbeque',
  'Basque',
  'Bavarian',
  'Beer Garden',
  'Beer Hall',
  'Beer, Wine & Spirits',
  'Beira',
  'Beisl',
  'Belgian',
  'Bento',
  'Berrichon',
  'Beverage Store',
  'Bistros',
  'Black Sea',
  'Blowfish',
  'Bourguignon',
  'Brasseries',
  'Brazilian',
  'Brazilian Empanadas',
  'Breakfast & Brunch',
  'Breweries',
  'Brewpubs',
  'British',
  'Bubble Tea',
  'Buffets',
  'Bulgarian',
  'Burgers',
  'Burmese',
  'Burrito',
  'Butcher',
  'Cafes',
  'Cafeteria',
  'Cajun/Creole',
  'Calabrian',
  'Cambodian',
  'Canadian',
  'Candy Stores',
  'Canteen',
  'Cantonese',
  'Caribbean',
  'Catalan',
  'Central Brazilian',
  'Chee Kufta',
  'Cheese Shops',
  'Cheesesteaks',
  'Chicken Shop',
  'Chicken Wings',
  'Chilean',
  'Chimney Cakes',
  'Chinese',
  'Chocolatiers & Shops',
  'Churros',
  'Cideries',
  'Coffee & Tea',
  'Coffee & Tea Supplies',
  'Coffee Roasteries',
  'Colombian',
  'Comfort Food',
  'Congee',
  'Conveyor Belt Sushi',
  'Corsican',
  'Creperies',
  'Cuban',
  'Cucina campana',
  'Cupcakes',
  'Curry Sausage',
  'Custom Cakes',
  'Cypriot',
  'Czech',
  'Czech/Slovakian',
  'Dagashi',
  'Danish',
  'Delicatessen',
  'Delis',
  'Desserts',
  'Dim Sum',
  'Diners',
  'Dinner Theater',
  'Distilleries',
  'Do-It-Yourself Food',
  'Dominican',
  'Donairs',
  'Donburi',
  'Donuts',
  'Dried Fruit',
  'Dumplings',
  'Eastern European',
  'Eastern German',
  'Eastern Mexican',
  'Egyptian',
  'Emilian',
  'Empanadas',
  'Eritrean',
  'Ethical Grocery',
  'Ethiopian',
  'Fado Houses',
  'Falafel',
  'Farmers Market',
  'Fast Food',
  'Filipino',
  'Fischbroetchen',
  'Fish & Chips',
  'Fishmonger',
  'Flatbread',
  'Flemish',
  'Fondue',
  'Food Court',
  'Food Delivery Services',
  'Food Stands',
  'Food Trucks',
  'Franconian',
  'Freiduria',
  'French',
  'French Southwest',
  'Friterie',
  'Friulan',
  'Frozen Food',
  'Fruits & Veggies',
  'Fuzhou',
  'Galician',
  'Game Meat',
  'Gastropubs',
  'Gelato',
  'Georgian',
  'German',
  'Giblets',
  'Gluten-Free',
  'Gozleme',
  'Greek',
  'Grocery',
  'Guamanian',
  'Gyudon',
  'Hainan',
  'Haitian',
  'Hakka',
  'Halal',
  'Hand Rolls',
  'Hawaiian',
  'Hawker Centre',
  'Health Markets',
  'Henghwa',
  'Herbs & Spices',
  'Hessian',
  'Heuriger',
  'Himalayan/Nepalese',
  'Hokkien',
  'Homemade Food',
  'Honduran',
  'Honey',
  'Hong Kong Style Cafe',
  'Horumon',
  'Hot Dogs',
  'Hot Pot',
  'Hunan',
  'Hungarian',
  'Iberian',
  'Ice Cream & Frozen Yogurt',
  'Imported Food',
  'Indian',
  'Indonesian',
  'International',
  'International Grocery',
  'Internet Cafes',
  'Irish',
  'Island Pub',
  'Israeli',
  'Italian',
  'Izakaya',
  'Jaliscan',
  'Japanese',
  'Japanese Curry',
  'Japanese Sweets',
  'Jewish',
  'Juice Bars & Smoothies',
  'Kaiseki',
  'Kebab',
  'Kiosk',
  'Kombucha',
  'Kopitiam',
  'Korean',
  'Kosher',
  'Kurdish',
  'Kushikatsu',
  'Lahmacun',
  'Laos',
  'Laotian',
  'Latin American',
  'Lebanese',
  'Ligurian',
  'Live/Raw Food',
  'Lumbard',
  'Lyonnais',
  'Macarons',
  'Madeira',
  'Malaysian',
  'Mamak',
  'Mauritius',
  'Meaderies',
  'Meat Shops',
  'Meatballs',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Milk Bars',
  'Milkshake Bars',
  'Minho',
  'Modern Australian',
  'Modern European',
  'Mongolian',
  'Moroccan',
  'Mulled Wine',
  'Napoletana',
  'Nasi Lemak',
  'New Mexican Cuisine',
  'New Zealand',
  'Nicaraguan',
  'Nicoise',
  'Night Food',
  'Nikkei',
  'Noodles',
  'Norcinerie',
  'Northeastern Brazilian',
  'Northern Brazilian',
  'Northern German',
  'Northern Mexican',
  'Nyonya',
  'Oaxacan',
  'Oden',
  'Okinawan',
  'Okonomiyaki',
  'Olive Oil',
  'Onigiri',
  'Open Sandwiches',
  'Organic Stores',
  'Oriental',
  'Ottoman Cuisine',
  'Oyakodon',
  'PF/Comercial',
  'Pakistani',
  'Palatine',
  'Pan Asian',
  'Pancakes',
  'Panzerotti',
  'Parent Cafes',
  'Parent Cafes',
  'Parma',
  'Pasta Shops',
  'Patisserie/Cake Shop',
  'Pekinese',
  'Persian/Iranian',
  'Peruvian',
  'Pho',
  'Piadina',
  'Piemonte',
  'Pierogis',
  'Pita',
  'Pizza',
  'Poke',
  'Polish',
  'Polynesian',
  'Pop-Up Restaurants',
  'Popcorn Shops',
  'Portuguese',
  'Potatoes',
  'Poutineries',
  'Pretzels',
  'Provencal',
  'Pub Food',
  'Pueblan',
  'Puerto Rican',
  'Ramen',
  'Reunion',
  'Rhinelandian',
  'Ribatejo',
  'Rice',
  'Robatayaki',
  'Rodizios',
  'Roman',
  'Romanian',
  'Rotisserie Chicken',
  'Russian',
  'Salad',
  'Salumerie',
  'Salvadoran',
  'Sandwiches',
  'Sardinian',
  'Scandinavian',
  'Schnitzel',
  'Scottish',
  'Seafood',
  'Seafood Markets',
  'Senegalese',
  'Serbo Croatian',
  'Shanghainese',
  'Shaved Ice',
  'Shaved Snow',
  'Sicilian',
  'Signature Cuisine',
  'Singaporean',
  'Slovakian',
  'Smokehouse',
  'Soba',
  'Somali',
  'Soul Food',
  'Soup',
  'South African',
  'Southern',
  'Spanish',
  'Specialty Food',
  'Sri Lankan',
  'Steakhouses',
  'Street Vendors',
  'Sugar Shacks',
  'Sukiyaki',
  'Supper Clubs',
  'Sushi Bars',
  'Swabian',
  'Swedish',
  'Swiss Food',
  'Syrian',
  'Szechuan',
  'Tabernas',
  'Tacos',
  'Taiwanese',
  'Taiyaki',
  'Takoyaki',
  'Tamales',
  'Tapas Bars',
  'Tapas/Small Plates',
  'Tavola Calda',
  'Tea Rooms',
  'Tempura',
  'Teochew',
  'Teppanyaki',
  'Tex-Mex',
  'Thai',
  'Themed Cafes',
  'Tofu Shops',
  'Tonkatsu',
  'Torshi',
  'Tortillas',
  'Traditional Norwegian',
  'Traditional Swedish',
  'Tras-os-Montes',
  'Trattorie',
  'Trinidadian',
  'Turkish',
  'Turkish Ravioli',
  'Tuscan',
  'Udon',
  'Ukrainian',
  'Unagi',
  'Uzbek',
  'Vegan',
  'Vegetarian',
  'Venetian',
  'Venezuelan',
  'Venison',
  'Vietnamese',
  'Waffles',
  'Water Stores',
  'Western Style Japanese Food',
  'Wine Tasting Room',
  'Wineries',
  'Wok',
  'Wraps',
  'Yakiniku',
  'Yakitori',
  'Yucatan',
  'Yugoslav',
  'Zapiekanka',
]

export default { tagTypes };
